/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategistRouteImport } from './routes/_authenticated/strategist'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedQuickBookRouteImport } from './routes/_authenticated/quick-book'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPhonesRouteImport } from './routes/_authenticated/phones'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIvrRouteImport } from './routes/_authenticated/ivr'
import { Route as AuthenticatedInvestorsRouteImport } from './routes/_authenticated/investors'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIdeasRouteImport } from './routes/_authenticated/ideas'
import { Route as AuthenticatedGrantsRouteImport } from './routes/_authenticated/grants'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAlienRouteImport } from './routes/_authenticated/alien'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicAllRouteImport } from './routes/api/public/all'
import { Route as ApiPublicProvisionFileRouteImport } from './routes/api/public/provision/$file'
import { Route as ApiPublicHooksYealinkCdrRouteImport } from './routes/api/public/hooks/yealink-cdr'
import { Route as ApiPublicHooksVoiceCallRouteImport } from './routes/api/public/hooks/voice-call'
import { Route as ApiPublicHooksStrategistRouteImport } from './routes/api/public/hooks/strategist'
import { Route as ApiPublicHooksDailySocialRouteImport } from './routes/api/public/hooks/daily-social'
import { Route as ApiPublicHooksDailyRemindersRouteImport } from './routes/api/public/hooks/daily-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategistRoute = AuthenticatedStrategistRouteImport.update({
  id: '/strategist',
  path: '/strategist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickBookRoute = AuthenticatedQuickBookRouteImport.update({
  id: '/quick-book',
  path: '/quick-book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhonesRoute = AuthenticatedPhonesRouteImport.update({
  id: '/phones',
  path: '/phones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIvrRoute = AuthenticatedIvrRouteImport.update({
  id: '/ivr',
  path: '/ivr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorsRoute = AuthenticatedInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeasRoute = AuthenticatedIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrantsRoute = AuthenticatedGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlienRoute = AuthenticatedAlienRouteImport.update({
  id: '/alien',
  path: '/alien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAllRoute = ApiPublicAllRouteImport.update({
  id: '/api/public/all',
  path: '/api/public/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProvisionFileRoute = ApiPublicProvisionFileRouteImport.update({
  id: '/api/public/provision/$file',
  path: '/api/public/provision/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksYealinkCdrRoute =
  ApiPublicHooksYealinkCdrRouteImport.update({
    id: '/api/public/hooks/yealink-cdr',
    path: '/api/public/hooks/yealink-cdr',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVoiceCallRoute = ApiPublicHooksVoiceCallRouteImport.update({
  id: '/api/public/hooks/voice-call',
  path: '/api/public/hooks/voice-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStrategistRoute =
  ApiPublicHooksStrategistRouteImport.update({
    id: '/api/public/hooks/strategist',
    path: '/api/public/hooks/strategist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailySocialRoute =
  ApiPublicHooksDailySocialRouteImport.update({
    id: '/api/public/hooks/daily-social',
    path: '/api/public/hooks/daily-social',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRemindersRoute =
  ApiPublicHooksDailyRemindersRouteImport.update({
    id: '/api/public/hooks/daily-reminders',
    path: '/api/public/hooks/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/alien': typeof AuthenticatedAlienRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/grants': typeof AuthenticatedGrantsRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investors': typeof AuthenticatedInvestorsRoute
  '/ivr': typeof AuthenticatedIvrRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/phones': typeof AuthenticatedPhonesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/quick-book': typeof AuthenticatedQuickBookRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategist': typeof AuthenticatedStrategistRoute
  '/api/public/all': typeof ApiPublicAllRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/daily-social': typeof ApiPublicHooksDailySocialRoute
  '/api/public/hooks/strategist': typeof ApiPublicHooksStrategistRoute
  '/api/public/hooks/voice-call': typeof ApiPublicHooksVoiceCallRoute
  '/api/public/hooks/yealink-cdr': typeof ApiPublicHooksYealinkCdrRoute
  '/api/public/provision/$file': typeof ApiPublicProvisionFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/alien': typeof AuthenticatedAlienRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/grants': typeof AuthenticatedGrantsRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investors': typeof AuthenticatedInvestorsRoute
  '/ivr': typeof AuthenticatedIvrRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/phones': typeof AuthenticatedPhonesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/quick-book': typeof AuthenticatedQuickBookRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategist': typeof AuthenticatedStrategistRoute
  '/api/public/all': typeof ApiPublicAllRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/daily-social': typeof ApiPublicHooksDailySocialRoute
  '/api/public/hooks/strategist': typeof ApiPublicHooksStrategistRoute
  '/api/public/hooks/voice-call': typeof ApiPublicHooksVoiceCallRoute
  '/api/public/hooks/yealink-cdr': typeof ApiPublicHooksYealinkCdrRoute
  '/api/public/provision/$file': typeof ApiPublicProvisionFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/alien': typeof AuthenticatedAlienRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/grants': typeof AuthenticatedGrantsRoute
  '/_authenticated/ideas': typeof AuthenticatedIdeasRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/investors': typeof AuthenticatedInvestorsRoute
  '/_authenticated/ivr': typeof AuthenticatedIvrRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/phones': typeof AuthenticatedPhonesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/quick-book': typeof AuthenticatedQuickBookRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategist': typeof AuthenticatedStrategistRoute
  '/api/public/all': typeof ApiPublicAllRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/daily-social': typeof ApiPublicHooksDailySocialRoute
  '/api/public/hooks/strategist': typeof ApiPublicHooksStrategistRoute
  '/api/public/hooks/voice-call': typeof ApiPublicHooksVoiceCallRoute
  '/api/public/hooks/yealink-cdr': typeof ApiPublicHooksYealinkCdrRoute
  '/api/public/provision/$file': typeof ApiPublicProvisionFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/alien'
    | '/approvals'
    | '/bookings'
    | '/calls'
    | '/connections'
    | '/customers'
    | '/dashboard'
    | '/feed'
    | '/grants'
    | '/ideas'
    | '/inventory'
    | '/investors'
    | '/ivr'
    | '/knowledge'
    | '/leads'
    | '/phones'
    | '/projects'
    | '/quick-book'
    | '/scripts'
    | '/services'
    | '/settings'
    | '/strategist'
    | '/api/public/all'
    | '/api/public/catalog'
    | '/api/public/ingest'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/daily-social'
    | '/api/public/hooks/strategist'
    | '/api/public/hooks/voice-call'
    | '/api/public/hooks/yealink-cdr'
    | '/api/public/provision/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/alien'
    | '/approvals'
    | '/bookings'
    | '/calls'
    | '/connections'
    | '/customers'
    | '/dashboard'
    | '/feed'
    | '/grants'
    | '/ideas'
    | '/inventory'
    | '/investors'
    | '/ivr'
    | '/knowledge'
    | '/leads'
    | '/phones'
    | '/projects'
    | '/quick-book'
    | '/scripts'
    | '/services'
    | '/settings'
    | '/strategist'
    | '/api/public/all'
    | '/api/public/catalog'
    | '/api/public/ingest'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/daily-social'
    | '/api/public/hooks/strategist'
    | '/api/public/hooks/voice-call'
    | '/api/public/hooks/yealink-cdr'
    | '/api/public/provision/$file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/alien'
    | '/_authenticated/approvals'
    | '/_authenticated/bookings'
    | '/_authenticated/calls'
    | '/_authenticated/connections'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/grants'
    | '/_authenticated/ideas'
    | '/_authenticated/inventory'
    | '/_authenticated/investors'
    | '/_authenticated/ivr'
    | '/_authenticated/knowledge'
    | '/_authenticated/leads'
    | '/_authenticated/phones'
    | '/_authenticated/projects'
    | '/_authenticated/quick-book'
    | '/_authenticated/scripts'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/strategist'
    | '/api/public/all'
    | '/api/public/catalog'
    | '/api/public/ingest'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/daily-social'
    | '/api/public/hooks/strategist'
    | '/api/public/hooks/voice-call'
    | '/api/public/hooks/yealink-cdr'
    | '/api/public/provision/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAllRoute: typeof ApiPublicAllRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicHooksDailyRemindersRoute: typeof ApiPublicHooksDailyRemindersRoute
  ApiPublicHooksDailySocialRoute: typeof ApiPublicHooksDailySocialRoute
  ApiPublicHooksStrategistRoute: typeof ApiPublicHooksStrategistRoute
  ApiPublicHooksVoiceCallRoute: typeof ApiPublicHooksVoiceCallRoute
  ApiPublicHooksYealinkCdrRoute: typeof ApiPublicHooksYealinkCdrRoute
  ApiPublicProvisionFileRoute: typeof ApiPublicProvisionFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategist': {
      id: '/_authenticated/strategist'
      path: '/strategist'
      fullPath: '/strategist'
      preLoaderRoute: typeof AuthenticatedStrategistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-book': {
      id: '/_authenticated/quick-book'
      path: '/quick-book'
      fullPath: '/quick-book'
      preLoaderRoute: typeof AuthenticatedQuickBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/phones': {
      id: '/_authenticated/phones'
      path: '/phones'
      fullPath: '/phones'
      preLoaderRoute: typeof AuthenticatedPhonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ivr': {
      id: '/_authenticated/ivr'
      path: '/ivr'
      fullPath: '/ivr'
      preLoaderRoute: typeof AuthenticatedIvrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investors': {
      id: '/_authenticated/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof AuthenticatedInvestorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ideas': {
      id: '/_authenticated/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AuthenticatedIdeasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grants': {
      id: '/_authenticated/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AuthenticatedGrantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alien': {
      id: '/_authenticated/alien'
      path: '/alien'
      fullPath: '/alien'
      preLoaderRoute: typeof AuthenticatedAlienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/all': {
      id: '/api/public/all'
      path: '/api/public/all'
      fullPath: '/api/public/all'
      preLoaderRoute: typeof ApiPublicAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provision/$file': {
      id: '/api/public/provision/$file'
      path: '/api/public/provision/$file'
      fullPath: '/api/public/provision/$file'
      preLoaderRoute: typeof ApiPublicProvisionFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/yealink-cdr': {
      id: '/api/public/hooks/yealink-cdr'
      path: '/api/public/hooks/yealink-cdr'
      fullPath: '/api/public/hooks/yealink-cdr'
      preLoaderRoute: typeof ApiPublicHooksYealinkCdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/voice-call': {
      id: '/api/public/hooks/voice-call'
      path: '/api/public/hooks/voice-call'
      fullPath: '/api/public/hooks/voice-call'
      preLoaderRoute: typeof ApiPublicHooksVoiceCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/strategist': {
      id: '/api/public/hooks/strategist'
      path: '/api/public/hooks/strategist'
      fullPath: '/api/public/hooks/strategist'
      preLoaderRoute: typeof ApiPublicHooksStrategistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-social': {
      id: '/api/public/hooks/daily-social'
      path: '/api/public/hooks/daily-social'
      fullPath: '/api/public/hooks/daily-social'
      preLoaderRoute: typeof ApiPublicHooksDailySocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reminders': {
      id: '/api/public/hooks/daily-reminders'
      path: '/api/public/hooks/daily-reminders'
      fullPath: '/api/public/hooks/daily-reminders'
      preLoaderRoute: typeof ApiPublicHooksDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAlienRoute: typeof AuthenticatedAlienRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGrantsRoute: typeof AuthenticatedGrantsRoute
  AuthenticatedIdeasRoute: typeof AuthenticatedIdeasRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvestorsRoute: typeof AuthenticatedInvestorsRoute
  AuthenticatedIvrRoute: typeof AuthenticatedIvrRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPhonesRoute: typeof AuthenticatedPhonesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedQuickBookRoute: typeof AuthenticatedQuickBookRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategistRoute: typeof AuthenticatedStrategistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAlienRoute: AuthenticatedAlienRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGrantsRoute: AuthenticatedGrantsRoute,
  AuthenticatedIdeasRoute: AuthenticatedIdeasRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvestorsRoute: AuthenticatedInvestorsRoute,
  AuthenticatedIvrRoute: AuthenticatedIvrRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPhonesRoute: AuthenticatedPhonesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedQuickBookRoute: AuthenticatedQuickBookRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategistRoute: AuthenticatedStrategistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAllRoute: ApiPublicAllRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicHooksDailyRemindersRoute: ApiPublicHooksDailyRemindersRoute,
  ApiPublicHooksDailySocialRoute: ApiPublicHooksDailySocialRoute,
  ApiPublicHooksStrategistRoute: ApiPublicHooksStrategistRoute,
  ApiPublicHooksVoiceCallRoute: ApiPublicHooksVoiceCallRoute,
  ApiPublicHooksYealinkCdrRoute: ApiPublicHooksYealinkCdrRoute,
  ApiPublicProvisionFileRoute: ApiPublicProvisionFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
